import type { WorkTask } from "./workdays";

export type CareerExperienceConfig = {
  slug: string; title: string; workplace: string; headline: string; intro: string;
  dayLabel: string; dayContext: string; guideName: string; guideRole: string;
  fictionNote: string; tasks: WorkTask[]; questions?: Record<string, string>;
  adjacent: string[]; peopleIntro: string;
  videos: { id: string; title: string; creator: string }[];
  sources: { label: string; description: string; url: string }[];
};

const pediatricianTasks: WorkTask[] = [
  {id:"well-visit",ticket:"VISIT-0830",priority:"ROUTINE",system:"Pediatric EHR",channel:"Exam room 3",time:"8:30 AM",title:"A parent is worried about development",situation:"A two-year-old is here for a well-child visit. The parent mentions limited speech and asks whether it is just a phase.",people:["You","Child","Parent","Medical assistant"],why:"Pediatricians combine observation, screening tools, family context, and careful communication to spot concerns early without causing unnecessary alarm.",duration:32,workType:"Investigation",outcome:"You complete a validated screen, discuss what it does and does not mean, and arrange hearing and early-intervention follow-up.",steps:[{label:"Build trust",minutes:5,detail:"Greet the child at eye level and ask the parent what changes they have noticed."},{label:"Examine and screen",minutes:12,detail:"Review growth, development, hearing risk, and a validated developmental questionnaire."},{label:"Explain",minutes:8,detail:"Describe the findings in plain language while avoiding a premature diagnosis."},{label:"Coordinate follow-up",minutes:7,detail:"Place referrals, document the plan, and give the family clear return precautions."}]},
  {id:"fever",ticket:"SAME-DAY-104",priority:"URGENT",system:"Acute care clinic",channel:"Exam room 6",time:"10:05 AM",title:"An infant arrives with a fever",situation:"A seven-week-old has a measured fever and is sleepier than usual. The family hopes to avoid the emergency department.",people:["You","Infant","Parents","Triage nurse"],why:"Young infants can become seriously ill quickly, so age, appearance, vital signs, and timely escalation matter more than reassurance alone.",duration:28,workType:"Planning",outcome:"You stabilize the infant, explain the risk clearly, call the receiving emergency team, and arrange immediate transfer for evaluation.",steps:[{label:"Assess stability",minutes:6,detail:"Repeat vital signs and quickly assess breathing, circulation, hydration, and responsiveness."},{label:"Gather focused history",minutes:7,detail:"Confirm temperature method, feeding, wet diapers, birth history, and exposures."},{label:"Choose the safe setting",minutes:6,detail:"Apply age-based fever guidance and explain why hospital testing is necessary."},{label:"Handoff",minutes:9,detail:"Call ahead with a concise clinical summary and document the transfer plan."}]},
  {id:"vaccine",ticket:"CARE-1145",priority:"COUNSEL",system:"Preventive care",channel:"Family consultation",time:"11:45 AM",title:"A family is hesitant about vaccines",situation:"A parent shares alarming social-media claims and asks to delay several recommended vaccines.",people:["You","Parent","Child","Nurse"],why:"Trust grows when clinicians listen first, identify the specific concern, explain evidence honestly, and preserve the relationship.",duration:24,workType:"Communication",outcome:"The parent agrees to two vaccines today and schedules a follow-up conversation for the remaining questions.",steps:[{label:"Ask and listen",minutes:6,detail:"Invite the parent to name the claim that worries them most without interrupting."},{label:"Acknowledge",minutes:4,detail:"Recognize that protecting their child is the goal you share."},{label:"Explain evidence",minutes:8,detail:"Compare known disease risks, common side effects, and rare serious reactions clearly."},{label:"Make a plan",minutes:6,detail:"Use shared decision-making, document consent, and keep the door open for follow-up."}]},
  {id:"asthma",ticket:"CALL-1420",priority:"FOLLOW-UP",system:"Patient portal · care plan",channel:"Nurse message queue",time:"2:20 PM",title:"A student keeps missing school with asthma",situation:"A school nurse reports repeated rescue-inhaler use. The chart shows two urgent-care visits and no recent controller-medication review.",people:["You","Parent","School nurse","Pharmacist"],why:"Good pediatric care happens beyond the exam room and often requires coordinating family, school, medication access, and follow-up.",duration:36,workType:"Communication",outcome:"You update the asthma action plan, address an insurance barrier, teach inhaler technique, and schedule reassessment.",steps:[{label:"Review the pattern",minutes:8,detail:"Check symptoms, refill history, urgent visits, triggers, and the current action plan."},{label:"Call the family",minutes:9,detail:"Clarify nighttime symptoms, technique, adherence, cost, and home exposures."},{label:"Coordinate",minutes:11,detail:"Work with the pharmacy and school nurse on access and a consistent plan."},{label:"Document and follow",minutes:8,detail:"Update the action plan and set a short-interval follow-up with warning signs."}]},
  {id:"safeguarding",ticket:"CONSULT-1610",priority:"SENSITIVE",system:"Hospital consult",channel:"Private team room",time:"4:10 PM",title:"An injury does not match the story",situation:"A young child has bruising in an unusual location, and the caregiver’s explanation changes during the visit.",people:["You","Child","Caregiver","Social worker"],why:"Pediatricians must protect children while staying objective, documenting precisely, and following mandatory-reporting procedures.",duration:48,workType:"Documentation",outcome:"You address urgent medical needs, document neutral findings, consult the child-protection team, and follow required reporting steps.",steps:[{label:"Ensure immediate safety",minutes:8,detail:"Treat urgent needs and separate medical assessment from assumptions about cause."},{label:"Take a careful history",minutes:12,detail:"Use open questions and record who provided each statement."},{label:"Examine and document",minutes:14,detail:"Record objective findings precisely using the approved clinical process."},{label:"Consult and report",minutes:14,detail:"Involve the specialist team and follow local safeguarding requirements."}]},
];

const psychologistTasks: WorkTask[] = [
  {id:"intake",ticket:"INTAKE-0900",priority:"NEW CLIENT",system:"Secure clinical record",channel:"Therapy room",time:"9:00 AM",title:"A client says, “I can’t keep doing this”",situation:"During a first appointment, a college student describes hopelessness, poor sleep, and falling grades, then uses an ambiguous phrase about not continuing.",people:["You","Client"],why:"Psychologists create connection while directly assessing safety, symptoms, strengths, and context.",duration:55,workType:"Investigation",outcome:"You complete a collaborative risk assessment, identify protective supports, create a safety plan, and agree on next steps.",steps:[{label:"Slow down and connect",minutes:10,detail:"Reflect what you heard and ask permission to explore the statement directly."},{label:"Assess risk",minutes:18,detail:"Ask clearly about thoughts, intent, plans, access, history, substance use, and protective factors."},{label:"Plan together",minutes:17,detail:"Build a practical safety plan with coping steps, contacts, and crisis resources."},{label:"Document and follow",minutes:10,detail:"Record the assessment and rationale, then arrange appropriate follow-up."}]},
  {id:"assessment",ticket:"ASSESS-1030",priority:"EVALUATION",system:"Testing workspace",channel:"Assessment office",time:"10:30 AM",title:"Test results do not tell one simple story",situation:"An adolescent’s attention scores are mixed. Anxiety, sleep loss, language background, and classroom reports may all affect the pattern.",people:["You","Student","Parent","Teacher"],why:"Psychological assessment is interpretation, not just scoring; conclusions must integrate multiple data sources and limitations.",duration:74,workType:"Investigation",outcome:"You form a cautious, evidence-based explanation and recommend school supports while gathering more information before assigning a diagnosis.",steps:[{label:"Check validity",minutes:14,detail:"Review effort, testing conditions, norms, language factors, and score consistency."},{label:"Integrate sources",minutes:22,detail:"Compare interview, behavior, rating scales, records, and school observations."},{label:"Consider alternatives",minutes:18,detail:"Weigh attention disorder against anxiety, sleep, learning, and environmental explanations."},{label:"Write useful findings",minutes:20,detail:"Explain conclusions, uncertainty, strengths, and actionable recommendations."}]},
  {id:"session",ticket:"THERAPY-1300",priority:"SESSION",system:"CBT care plan",channel:"Therapy room",time:"1:00 PM",title:"A client avoids the exercise you planned",situation:"A client with panic symptoms did not attempt the agreed exposure exercise and now wants reassurance that avoidance is safer.",people:["You","Client"],why:"Therapy requires empathy and flexibility without accidentally reinforcing the pattern that keeps fear strong.",duration:50,workType:"Communication",outcome:"You explore the barrier without blame, revise the exposure into a manageable step, and practice it together.",steps:[{label:"Explore, do not scold",minutes:10,detail:"Ask what happened before, during, and after the decision not to practice."},{label:"Map the cycle",minutes:12,detail:"Connect sensations, predictions, avoidance, short-term relief, and long-term anxiety."},{label:"Adjust collaboratively",minutes:13,detail:"Choose a smaller exposure that is difficult but achievable and meaningful."},{label:"Practice and review",minutes:15,detail:"Run the exercise, gather learning, and agree on a specific home plan."}]},
  {id:"consult",ticket:"CONSULT-1440",priority:"TEAM",system:"Integrated care",channel:"Case conference",time:"2:40 PM",title:"The care team disagrees about the next step",situation:"A physician favors medication changes, a parent wants testing, and the teenager wants privacy and fewer appointments.",people:["You","Teen client","Parent","Physician"],why:"Psychologists often translate different perspectives while protecting consent, confidentiality, and the client’s voice.",duration:38,workType:"Planning",outcome:"The team agrees on a staged plan that preserves confidentiality boundaries, tracks symptoms, and revisits medication and testing with new data.",steps:[{label:"Clarify the question",minutes:7,detail:"Separate immediate safety, treatment preference, diagnostic uncertainty, and family concerns."},{label:"Center the client",minutes:9,detail:"Invite the teenager’s goals and explain the limits of confidentiality."},{label:"Translate evidence",minutes:12,detail:"Summarize what current data supports and what remains uncertain."},{label:"Agree and record",minutes:10,detail:"Define the plan, measures, responsibilities, and review date."}]},
  {id:"notes",ticket:"ADMIN-1630",priority:"RECORD",system:"Clinical documentation",channel:"Private office",time:"4:30 PM",title:"Finish notes without losing the human story",situation:"You have several sessions to document, a referral letter due, and only limited time before the next client message arrives.",people:["You","Referring clinician"],why:"Clear, timely records support continuity and safety, but clinical notes must also protect privacy and avoid unnecessary detail.",duration:42,workType:"Documentation",outcome:"You complete concise notes, document clinical reasoning and risk where relevant, and send a focused referral summary with consent.",steps:[{label:"Prioritize",minutes:6,detail:"Handle time-sensitive risk and coordination items before routine administration."},{label:"Write the clinical core",minutes:18,detail:"Capture interventions, response, assessment, plan, and essential reasoning."},{label:"Protect privacy",minutes:8,detail:"Remove speculative or irrelevant details and confirm release-of-information scope."},{label:"Close the loop",minutes:10,detail:"Send the referral, track follow-up, and secure the record."}]},
];

export const pediatricianExperience: CareerExperienceConfig = {slug:"pediatrician",title:"Pediatrician",workplace:"Harbor Children’s Clinic",headline:"A Day as a Pediatrician",intro:"Step into a busy children’s clinic. Move between preventive care, urgent decisions, family conversations, coordination, and child safety.",dayLabel:"Wednesday · General Pediatrics",dayContext:"Clinic + hospital consult",guideName:"Dr. Maya",guideRole:"Pediatrician",fictionNote:"Harbor Children’s Clinic is fictional. Scenarios model common pediatric workflows and are educational, not medical advice.",tasks:pediatricianTasks,questions:Object.fromEntries(pediatricianTasks.map(t=>[t.id,t.situation+" Would you take this case?"])),adjacent:["Family Physician","Child Life Specialist","Pediatric Nurse Practitioner","Public Health Physician"],peopleIntro:"Hear from practicing pediatricians, then compare the experience with trusted career data.",videos:[{id:"_c8WZZYk85o",title:"A Day in the Life of a Pediatrician",creator:"Indeed"},{id:"oo1Udt49WeI",title:"A Day in General Pediatrics",creator:"Nationwide Children’s Hospital"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/healthcare/physicians-and-surgeons.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/29-1221.00"}]};

export const psychologistExperience: CareerExperienceConfig = {slug:"psychologist",title:"Psychologist",workplace:"Northstar Behavioral Health",headline:"A Day as a Psychologist",intro:"Join a behavioral-health practice for a day of assessment, therapy, consultation, safety decisions, and careful documentation.",dayLabel:"Thursday · Clinical Psychology",dayContext:"Sessions + assessment",guideName:"Dr. Jordan",guideRole:"Psychologist",fictionNote:"Northstar Behavioral Health is fictional. Scenarios model common professional workflows and are educational, not mental-health advice.",tasks:psychologistTasks,questions:Object.fromEntries(psychologistTasks.map(t=>[t.id,t.situation+" Would you take this one?"])),adjacent:["School Psychologist","Clinical Social Worker","Psychiatrist","Behavioral Researcher"],peopleIntro:"Hear from working psychologists, then compare the experience with trusted career data.",videos:[{id:"y4JM0fFPql8",title:"Inside Therapy Sessions & Daily Routine",creator:"The Psych Diaries"},{id:"ljotdz5loDE",title:"A Day in the Life of a Clinical Psychologist",creator:"Tahatū Career Navigator"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/life-physical-and-social-science/psychologists.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/19-3033.00"}]};

export { registeredNurseExperience, dataScientistExperience, mechanicalEngineerExperience, highSchoolTeacherExperience, lawyerExperience } from "./careerExperiencesBatch1";
export { accountantExperience, electricianExperience, physicalTherapistExperience, marketingManagerExperience, architectExperience } from "./careerExperiencesBatch2";
