import type { CareerExperienceConfig } from "./careerExperiences";
import type { WorkTask, WorkType } from "./workdays";

type Moment = [string,string,string,string,string,string,string[],string,number,WorkType,string,[string,number,string][]];
const makeTasks = (items: Moment[]): WorkTask[] => items.map(([id,ticket,time,title,situation,why,people,channel,duration,workType,outcome,steps]) => ({id,ticket,priority:"REAL WORK",system:"Professional workspace",channel,time,title,situation,why,people,duration,workType,outcome,steps:steps.map(([label,minutes,detail])=>({label,minutes,detail}))}));
const makeExperience = (meta: Omit<CareerExperienceConfig,"questions">): CareerExperienceConfig => ({...meta,questions:Object.fromEntries(meta.tasks.map(t=>[t.id,`${t.situation} Would you take this on?`]))});

const accountantTasks = makeTasks([
  ["close","CLOSE-090","8:30 AM","A reconciliation is off by $84,000","The bank balance and ledger no longer agree two days before month-end reporting.","Accountants trace differences to evidence instead of forcing entries to make totals match.",["You","Controller","Treasury analyst"],"Finance office",54,"Investigation","You find a duplicated cash entry, correct it with support, and add a control to prevent recurrence.",[["Reconcile",12,"Compare statements, ledger activity, dates, and outstanding items."],["Trace",18,"Follow the difference to source documents and system entries."],["Correct",12,"Prepare a supported correcting entry with review."],["Prevent",12,"Document the cause and strengthen the close checklist."]]],
  ["revenue","REV-241","10:00 AM","A contract does not fit the standard revenue template","A customer pays upfront, receives implementation work, and can cancel partway through the term.","Revenue timing depends on enforceable terms and performance obligations, not simply when cash arrives.",["You","Sales operations","Legal counsel"],"Contract review",63,"Investigation","You document the accounting conclusion, defer the appropriate amount, and flag a contract-language gap.",[["Read the agreement",16,"Identify promises, pricing, cancellation, and acceptance terms."],["Map obligations",18,"Separate distinct deliverables and determine when control transfers."],["Calculate",17,"Model timing, allocation, and alternative interpretations."],["Memo",12,"Record the conclusion, evidence, judgments, and approvals."]]],
  ["budget","PLAN-320","1:00 PM","A department forecast suddenly improves","A team cuts its projected costs, but the improvement comes from moving expenses into next quarter.","Accountants help leaders distinguish real operating change from timing shifts.",["You","Department lead","FP&A manager"],"Forecast meeting",39,"Communication","You separate timing from savings and present a transparent full-year view.",[["Clarify",7,"Ask what operational decision changed."],["Compare",10,"Bridge old and new forecasts by driver."],["Challenge",10,"Test timing, commitments, and downstream effects."],["Explain",12,"Show quarterly and full-year impact without blame."]]],
  ["controls","CTRL-188","2:45 PM","One employee can create and pay a vendor","A process review reveals that the same person can add suppliers, approve invoices, and release payments.","Internal controls reduce error and fraud by separating incompatible duties and preserving evidence.",["You","Accounts payable lead","IT administrator"],"Controls review",46,"Planning","You design approval, access, and monitoring controls while keeping urgent payments workable.",[["Map access",10,"Document who can initiate, approve, change, and pay."],["Assess risk",10,"Identify plausible errors and misuse."],["Design controls",16,"Separate duties and add independent review."],["Test",10,"Verify the new workflow and retain evidence."]]],
  ["audit","AUD-515","4:15 PM","An auditor requests support that does not exist","A material estimate was approved in a meeting, but no one recorded the assumptions or review.","Audit-ready accounting requires contemporaneous evidence and honest treatment of gaps.",["You","External auditor","Controller"],"Audit portal",48,"Documentation","You disclose the documentation gap, reconstruct evidence carefully, and formalize future review.",[["Define request",7,"Confirm the assertion, period, and evidence needed."],["Gather evidence",14,"Collect source data, emails, calculations, and approvals."],["Be transparent",11,"Separate contemporaneous support from later reconstruction."],["Remediate",16,"Create a documented estimate and review control."]]],
]);

const electricianTasks = makeTasks([
  ["brief","JOB-0715","7:15 AM","The drawing and panel schedule disagree","A renovation print labels a circuit differently from the live panel directory.","Electricians verify conditions and de-energization rather than trusting labels alone.",["You","Foreperson","Apprentice"],"Commercial jobsite",31,"Planning","You stop the start, identify the correct circuit, update the briefing, and mark the discrepancy.",[["Review",6,"Compare scope, drawings, permits, and known hazards."],["Identify",8,"Trace the circuit using approved methods."],["Isolate",9,"Follow lockout/tagout and verify absence of voltage."],["Brief",8,"Update the team and documentation before work begins."]]],
  ["fault","SERVICE-204","9:20 AM","A breaker keeps tripping","A restaurant resets a kitchen breaker repeatedly and asks for a larger breaker.","Overcurrent protection signals a problem; changing its rating without analysis can create fire risk.",["You","Restaurant manager","Service electrician"],"Service call",57,"Investigation","You identify an overloaded circuit and damaged receptacle, repair safely, and propose load redistribution.",[["Make safe",7,"Stop repeated resets and control the area."],["Inspect",16,"Check loads, conductor size, terminations, heat, and damage."],["Test",18,"Measure under controlled conditions and isolate the fault."],["Repair",16,"Correct the defect, test protection, label, and explain limits."]]],
  ["install","ROUGH-331","11:30 AM","A conduit route collides with plumbing","The planned route cannot maintain access and clearance around other building systems.","Electrical installation requires code compliance and coordination with the whole building.",["You","Plumber","General contractor"],"Coordination walk",42,"Communication","The trades agree on a reroute that protects clearances, access, schedule, and future maintenance.",[["Verify conflict",8,"Measure actual conditions against coordinated drawings."],["Check constraints",10,"Confirm code, bend, fill, access, and structural limits."],["Coordinate",12,"Compare routes with affected trades."],["Record",12,"Mark the agreed route and update the field plan."]]],
  ["test","TEST-447","2:10 PM","A new circuit fails insulation testing","A completed run shows an unexpected reading before energization.","Testing before energization catches damage while it can still be corrected safely.",["You","Apprentice","Quality inspector"],"Electrical room",49,"Investigation","You section the run, find conductor damage at a pull point, replace it, and retest successfully.",[["Keep de-energized",5,"Preserve isolation and verify test conditions."],["Validate setup",9,"Confirm instrument, range, connections, and sensitive equipment."],["Section the run",19,"Narrow the fault by testing safe subsections."],["Repair and retest",16,"Replace damage and record final values."]]],
  ["handover","TURNOVER-602","4:00 PM","Labels and as-built drawings are incomplete","The system works, but turnover documents do not match field changes.","Safe operation and maintenance depend on accurate labeling, testing records, and as-builts.",["You","Foreperson","Facility manager"],"Turnover review",44,"Documentation","You reconcile field conditions, labels, test results, and drawings before sign-off.",[["Walk down",10,"Compare installed equipment with plans and schedules."],["Correct labels",12,"Use durable, unambiguous identifiers."],["Compile tests",10,"Attach inspection and commissioning records."],["Handover",12,"Explain isolation points, exceptions, and maintenance needs."]]],
]);

const therapistTasks = makeTasks([
  ["evaluation","PT-0800","8:00 AM","Back pain comes with an unexpected warning sign","A new patient expects exercises, but reports recent unexplained weight loss and worsening night pain.","Physical therapists screen for conditions that require medical evaluation before treatment.",["You","Patient","Primary-care clinician"],"Evaluation room",51,"Investigation","You pause routine treatment, complete a focused screen, and arrange timely medical follow-up.",[["Listen",10,"Clarify onset, behavior, medical history, and patient goals."],["Screen",15,"Check relevant systems, symptoms, and urgent warning signs."],["Decide",12,"Determine whether treatment, referral, or emergency action is appropriate."],["Coordinate",14,"Explain the concern and document a clear handoff."]]],
  ["plan","PT-0945","9:45 AM","The patient’s goal is not the clinic’s default goal","After knee surgery, the patient cares most about kneeling for work, not a generic walking score.","Effective rehabilitation connects measurable impairments with activities meaningful to the patient.",["You","Patient","Orthopedic surgeon"],"Treatment gym",47,"Planning","You build a staged plan around safe mobility, strength, kneeling tolerance, and return-to-work demands.",[["Define goals",9,"Ask what successful recovery enables in daily life."],["Measure baseline",12,"Assess motion, strength, swelling, function, and precautions."],["Plan progression",15,"Select exercises and milestones tied to the goal."],["Share decisions",11,"Agree on home practice, load limits, and review dates."]]],
  ["session","PT-1130","11:30 AM","Pain rises during a planned exercise","A patient’s shoulder pain increases and movement quality changes midway through loading.","Therapists continuously reassess response and adjust dosage rather than blindly finishing a protocol.",["You","Patient","Physical therapist assistant"],"Treatment gym",43,"Communication","You stop, reassess, modify the movement and load, and confirm a tolerable home plan.",[["Pause",5,"Stop the provoking movement and ask what changed."],["Reassess",11,"Check symptoms, motion, strength, and technique."],["Modify",15,"Change range, resistance, support, or exercise selection."],["Teach",12,"Confirm understanding and define acceptable response afterward."]]],
  ["team","REHAB-260","1:50 PM","The discharge team disagrees about safety","A hospitalized patient walks well in therapy but remains confused at night and lives alone.","Mobility is only one part of safe discharge; therapists integrate function, cognition, environment, and support.",["You","Patient","Nurse","Case manager"],"Care conference",38,"Communication","The team arranges supervised discharge and home-safety follow-up instead of relying on one good session.",[["Share evidence",8,"Describe assistance, endurance, cognition, and variability."],["Hear context",8,"Gather nursing, family, and home-environment information."],["Compare options",12,"Weigh support, equipment, setting, and follow-up."],["Document plan",10,"Record recommendations and unresolved risks clearly."]]],
  ["notes","NOTE-430","4:30 PM","Show progress without overstating it","Insurance review is due, but function improved less than expected despite regular attendance.","Clinical records must connect objective change, skilled care, barriers, and the next decision honestly.",["You","Patient","Utilization reviewer"],"Clinical record",41,"Documentation","You document measured progress, barriers, revised goals, and why continued or changed care is appropriate.",[["Compare",9,"Use consistent measures against baseline and goals."],["Explain",12,"Connect interventions and response without copying generic text."],["Reassess plan",10,"Address barriers and modify dosage or referral."],["Submit",10,"Write a concise, accurate progress report."]]],
]);

const marketingTasks = makeTasks([
  ["brief","MKT-101","8:45 AM","The campaign goal is too vague","Leadership asks for a campaign that will ‘make the brand go viral’ next month.","Marketing managers turn ambition into a defined audience, behavior, message, budget, and measure.",["You","Brand lead","Sales lead"],"Campaign kickoff",44,"Planning","You replace the viral goal with an audience-specific acquisition objective and guardrails.",[["Clarify outcome",9,"Ask which audience behavior and business result matter."],["Study audience",10,"Use research and existing evidence, not stereotypes."],["Set strategy",14,"Define positioning, channel roles, offer, and budget."],["Measure",11,"Choose leading, outcome, and brand-safety metrics."]]],
  ["creative","CREATIVE-230","10:15 AM","A clever concept misses the audience","The agency presents a polished idea that customers in testing find confusing and dismissive.","Marketing decisions balance creative quality with audience evidence and brand meaning.",["You","Creative director","Researcher","Agency"],"Creative review",39,"Communication","You preserve the strongest visual idea, rewrite the promise, and schedule a focused retest.",[["Return to brief",7,"Restate audience, insight, promise, and required action."],["Read evidence",10,"Separate preference from repeated comprehension problems."],["Give direction",12,"Explain what must change without prescribing every detail."],["Retest",10,"Define the next learning question and approval gate."]]],
  ["launch","LAUNCH-344","12:30 PM","A landing page breaks before launch","Paid media is scheduled, but mobile checkout fails and analytics events are duplicated.","Campaign launch requires operational readiness, measurement integrity, and the willingness to hold spend.",["You","Web developer","Analyst","Media buyer"],"Launch channel",52,"Planning","You pause the campaign, triage revenue and tracking issues, retest, and release in stages.",[["Stop spend",5,"Prevent traffic from reaching a broken journey."],["Triage",13,"Separate customer blockers from measurement defects."],["Verify fixes",19,"Test devices, paths, events, consent, and fallbacks."],["Stage launch",15,"Start small with monitoring and rollback ownership."]]],
  ["performance","REPORT-419","2:20 PM","Clicks are up while sales are down","A social campaign beats engagement targets but produces low-quality traffic and fewer purchases.","Marketing managers connect channel metrics to customer behavior and commercial outcomes.",["You","Performance marketer","Sales operations"],"Performance review",48,"Investigation","You find mismatched targeting and message intent, shift budget, and define a conversion-quality test.",[["Validate data",10,"Check attribution, tracking, timing, and comparison periods."],["Follow funnel",13,"Locate where behavior differs from qualified traffic."],["Form hypotheses",11,"Test audience, creative promise, offer, and landing experience."],["Act",14,"Reallocate cautiously and define evaluation criteria."]]],
  ["issue","SOCIAL-588","4:05 PM","A scheduled post lands during a crisis","An upbeat promotional post publishes while breaking news directly affects the community you serve.","Brand stewardship requires context, fast judgment, respectful communication, and controlled approvals.",["You","Communications lead","Community manager"],"Response room",36,"Communication","You pause scheduled content, remove the post, acknowledge the mistake, and coordinate an appropriate response.",[["Pause",4,"Stop queued promotional content across channels."],["Assess",8,"Verify context, audience impact, and current reach."],["Coordinate",11,"Align communications, legal, service, and leadership owners."],["Respond and learn",13,"Act proportionately and update the crisis checklist."]]],
]);

const architectTasks = makeTasks([
  ["brief","ARC-110","8:30 AM","The client’s wish list exceeds the site","A community center needs more rooms than zoning, budget, and the parcel can comfortably support.","Architects translate aspirations and constraints into priorities before drawing a preferred solution.",["You","Client committee","Planner"],"Programming workshop",51,"Planning","You build a ranked program, identify code and site limits, and agree on options to test.",[["Listen",11,"Understand users, activities, adjacencies, identity, and future change."],["Verify constraints",13,"Check site, zoning, accessibility, budget, and schedule."],["Prioritize",14,"Separate essential outcomes from preferred features."],["Frame options",13,"Document assumptions and concepts for comparison."]]],
  ["design","SD-245","10:10 AM","A beautiful concept creates poor daylight","The preferred massing looks strong in renderings but leaves key classrooms dark for much of the day.","Design quality combines form with measurable comfort, performance, use, and context.",["You","Design lead","Sustainability consultant"],"Design studio",67,"Investigation","You test orientation and section changes, preserve the core idea, and improve useful daylight.",[["Measure",14,"Review sun path, glare, depth, orientation, and target spaces."],["Generate",19,"Sketch multiple massing, opening, and section alternatives."],["Test",20,"Compare daylight, energy, structure, area, and cost implications."],["Present",14,"Show the tradeoff clearly and recommend an option."]]],
  ["coordination","BIM-377","1:00 PM","Structure and ventilation occupy the same space","A coordination model shows a major duct crossing a beam above a low ceiling.","Architects coordinate disciplines so building systems work together without sacrificing code or experience.",["You","Structural engineer","Mechanical engineer"],"BIM meeting",45,"Communication","The team revises routing and ceiling zones, then assigns model updates and verification.",[["Locate",8,"Confirm exact clash, tolerances, and affected rooms."],["Protect intent",9,"State critical clearance, ceiling, access, and performance needs."],["Compare solutions",15,"Evaluate routing, depth, openings, and localized design changes."],["Close loop",13,"Assign updates, deadlines, and a new clash check."]]],
  ["site","RFI-492","2:40 PM","The contractor finds an undocumented condition","Demolition reveals an old column where a new accessible route was planned.","Construction administration requires timely field judgment while respecting contracts, safety, and design authority.",["You","Contractor","Structural engineer","Owner"],"Construction site",56,"Investigation","You document the condition, coordinate structural facts, and issue a reviewed response with cost implications.",[["Observe",10,"Photograph, measure, and distinguish facts from assumptions."],["Check documents",12,"Review surveys, drawings, specifications, and responsibility."],["Coordinate",17,"Develop options with relevant consultants and contractor input."],["Respond formally",17,"Issue clear direction through the project process."]]],
  ["submittal","SUB-615","4:20 PM","A substitution looks similar but performs differently","A proposed exterior panel matches the color but has different fire, weathering, and attachment data.","Architects review submittals for conformance to design requirements—not merely appearance.",["You","Contractor","Envelope consultant"],"Submittal review",43,"Documentation","You reject the incomplete substitution and list the performance evidence needed for reconsideration.",[["Check scope",7,"Confirm what was specified and why."],["Compare data",13,"Review fire, weather, finish, warranty, attachment, and testing."],["Assess interfaces",11,"Consider adjacent assemblies and code requirements."],["Record decision",12,"Mark deviations and communicate required next steps."]]],
]);

export const accountantExperience = makeExperience({slug:"accountant",title:"Accountant",workplace:"Meridian Finance Group",headline:"A Day as an Accountant",intro:"Follow the evidence through close, revenue, forecasting, controls, and audit support.",dayLabel:"Monday · Corporate Accounting",dayContext:"Month-end close",guideName:"Elena",guideRole:"Accountant",fictionNote:"Meridian Finance Group is fictional. Scenarios model common accounting work and are educational.",tasks:accountantTasks,adjacent:["Financial Analyst","Auditor","Controller","Forensic Accountant"],peopleIntro:"See an accountant’s day, then compare it with official career data.",videos:[{id:"Abi56urip1M",title:"A Day in the Life of an Accountant",creator:"Indeed"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/business-and-financial/accountants-and-auditors.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/13-2011.00"}]});
export const electricianExperience = makeExperience({slug:"electrician",title:"Electrician",workplace:"Northline Electrical",headline:"A Day as an Electrician",intro:"Work safely through circuit identification, fault finding, installation coordination, testing, and turnover.",dayLabel:"Tuesday · Commercial Service",dayContext:"Jobsite + service calls",guideName:"Marcus",guideRole:"Electrician",fictionNote:"Northline Electrical is fictional. Scenarios are educational; electrical work requires qualified supervision and local-code compliance.",tasks:electricianTasks,adjacent:["Electrical Technician","Line Installer","HVAC Technician","Construction Manager"],peopleIntro:"Explore the practical work, then compare it with trusted career data.",videos:[{id:"lifunadBZ3U",title:"A Day in the Life of an Electrician",creator:"Indeed"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/construction-and-extraction/electricians.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/47-2111.00"}]});
export const physicalTherapistExperience = makeExperience({slug:"physical-therapist",title:"Physical Therapist",workplace:"MotionWorks Rehabilitation",headline:"A Day as a Physical Therapist",intro:"Assess, plan, adapt treatment, coordinate discharge, and document meaningful functional change.",dayLabel:"Wednesday · Outpatient + hospital",dayContext:"Evaluation and treatment",guideName:"Dr. Taylor",guideRole:"Physical Therapist",fictionNote:"MotionWorks Rehabilitation is fictional. Scenarios are educational, not medical advice.",tasks:therapistTasks,adjacent:["Occupational Therapist","Athletic Trainer","Physician Assistant","Rehabilitation Counselor"],peopleIntro:"See physical therapy in practice, then explore official occupation data.",videos:[{id:"7u-_-5Zb1Qw",title:"A Day in the Life of a Physical Therapist",creator:"Spear Physical Therapy"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/healthcare/physical-therapists.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/29-1123.00"}]});
export const marketingManagerExperience = makeExperience({slug:"marketing-manager",title:"Marketing Manager",workplace:"Brightline Brand Studio",headline:"A Day as a Marketing Manager",intro:"Turn audience insight into a campaign, guide creative work, launch safely, interpret performance, and protect the brand.",dayLabel:"Thursday · Integrated Marketing",dayContext:"Campaign launch",guideName:"Ron",guideRole:"Marketing Manager",fictionNote:"Brightline Brand Studio is fictional. Scenarios reflect common marketing workflows.",tasks:marketingTasks,adjacent:["Market Research Analyst","Brand Strategist","Product Marketing Manager","Public Relations Manager"],peopleIntro:"Watch a real marketing manager at work, then compare official career data.",videos:[{id:"ydvowqCgiRo",title:"A Day in the Life of a Marketing Manager",creator:"Indeed"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/management/advertising-promotions-and-marketing-managers.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/11-2021.00"}]});
export const architectExperience = makeExperience({slug:"architect",title:"Architect",workplace:"Field & Form Studio",headline:"A Day as an Architect",intro:"Shape a project from client brief and design studies through technical coordination and construction decisions.",dayLabel:"Friday · Architecture Studio",dayContext:"Design + construction",guideName:"Mina",guideRole:"Architect",fictionNote:"Field & Form Studio is fictional. Scenarios model common architectural practice.",tasks:architectTasks,adjacent:["Urban Planner","Interior Designer","Landscape Architect","Construction Manager"],peopleIntro:"See an architect’s varied workday, then explore trusted career data.",videos:[{id:"_C5vCGB8Xx0",title:"A Day in the Life of an Architect",creator:"30X40 Design Workshop"}],sources:[{label:"BLS",description:"Pay, outlook & work environment",url:"https://www.bls.gov/ooh/architecture-and-engineering/architects.htm"},{label:"O*NET",description:"Tasks, skills & work activities",url:"https://www.onetonline.org/link/summary/17-1011.00"}]});
